const GET_ALL_STATS = "GET_ALL_STATS"
const ADD_NODE = "ADD_NODE"
const REMOVE_CLUSTER_NODE = "REMOVE_CLUSTER_NODE"
const SYNC = "SYNC"

const GET_FILESTRUCTURE = "GET_FILESTRUCTURE"
const RMPIN = "RMPIN"


module.exports = {
    GET_ALL_STATS,
    ADD_NODE,
    REMOVE_CLUSTER_NODE,
    SYNC,
    GET_FILESTRUCTURE,
    RMPIN
}