const GET_ALL_STATS = "GET_ALL_STATS"
const ADD_NODE = "ADD_NODE"
const REMOVE_NODE = "REMOVE_NODE"
const SYNC = "SYNC"
const GET_FILESTRUCTURE = "GET_FILESTRUCTURE"

module.exports = {
    GET_ALL_STATS,
    ADD_NODE,
    REMOVE_NODE,
    SYNC,
    GET_FILESTRUCTURE
}